### ISSUE TITLE
"failed to load map! Umap appears to be an asset file"

### ISSUE THREAD

**Issue by MrMechanical** [sutongkui/SubPhysicsDemo#2]
I am unsure of how to fix this.

**Comment by sutongkui** [comment]
Sorry for the bug and too busy for me to maintain this repo recently. The most important thing is that i found it's not stable, also i make the training repo public https://github.com/sutongkui/SubPhysics. Maybe you can try to train it yourself and then implement in UE4

**Comment by MrMechanical** [comment]
Thank you for your help! I'll check it out.

**Comment by MrMechanical** [comment]
Your work is incredible. Does it work with any particle position input (even if it involves plastic deformation)?

**Comment by sutongkui** [comment]
Of course, it works for any primitive, including particle, mesh ... (For the mesh, we just use its vertices and don't care its topology).  The input to the network is vertices position, which means it works for anything that can be expressed with vertices.

**Comment by MrMechanical** [comment]
This is very cool. How about fracturing rigidbodies (expressed as particles)/tearing cloth? Thank you for your response.

**Comment by sutongkui** [comment]
I have been doing cloth simulation in the college. I think it's hard to get the tearing cloth result in this method. To get a good tearing result, you need to update the vertices position and mesh topology. The latter is not supported in this paper.  Maybe you can try other method.

**Comment by Abeetzer** [comment]
> Your work is incredible. Does it work with any particle position input (even if it involves plastic deformation)?

Dear MrMechanical,
How did you train the data and put it in a simulation because I want to implement the network in my game in UE4. I am trying to implement Subspace neural physics myself, but I do not know where to start. Any help or guidance will be highly appreciated.
