### ISSUE TITLE
Question about the collision artifacts

### ISSUE THREAD

**Issue by dytan** [sutongkui/SubPhysicsDemo#3]
Hello, noticed you have worked on Holden's subphysics demo. May I ask what the accuracy you gotten? Seems you experimented the 'ball collide mesh' on unreal engine, how do you deal with the 'visible intersection artifacts', is there need a 'projection collision' post process?

**Comment by sutongkui** [comment]
It's not precise and also not stable in my traning. The advantage of this method is the speed which makes it possible to work on mobile, if we add colliison process, it may become slowly.  Also i made the traning repo public https://github.com/sutongkui/SubPhysics

**Comment by dytan** [comment]
Sorry for the late notice, thank you!

**Comment by dytan** [comment]
Sorry for the late notice, thank you!
